version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./src:/src/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: subscription_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  python:
    image: python:3.11
    env_file: .env
    working_dir: /src/app
    volumes:
      - ./:/src/app

volumes:
  db_data:
